# Generated by Django 5.1.2 on 2024-11-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
                ('InicioPeriodo', models.DateField()),
                ('FinPeriodo', models.DateField()),
                ('TipoEvento', models.CharField(choices=[('exam', 'Examen'), ('holiday', 'Feriado'), ('admin', 'Administrativo')], max_length=50)),
            ],
        ),
    ]
