# Generated by Django 5.1.3 on 2024-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_academicevent_eventoacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('TipoEvento', models.CharField(choices=[('inicio_semestre', 'Inicio de Semestre'), ('fin_semestre', 'Fin de Semestre'), ('inicio_inscripcion', 'Inicio de Inscripción de Asignaturas'), ('fin_inscripcion', 'Fin de Inscripción de Asignaturas'), ('receso_academico', 'Receso Académico'), ('feriado_nacional', 'Feriado Nacional'), ('feriado_regional', 'Feriado Regional'), ('inicio_solicitudes', 'Inicio de Plazos de Solicitudes Administrativas'), ('fin_solicitudes', 'Fin de Plazos de Solicitudes Administrativas'), ('inicio_beneficios', 'Inicio de Plazos para la Gestión de Beneficios'), ('fin_beneficios', 'Fin de Plazos para la Gestión de Beneficios'), ('ceremonia_titulacion', 'Ceremonia de Titulación o Graduación'), ('reunion_consejo', 'Reunión de Consejo Académico'), ('talleres_charlas', 'Talleres y Charlas'), ('dia_orientacion', 'Día de Orientación para Nuevos Estudiantes'), ('eventos_extracurriculares', 'Eventos Extracurriculares'), ('inicio_clases', 'Inicio de Clases'), ('ultimo_dia_clases', 'Último Día de Clases'), ('dia_puertas_abiertas', 'Día de Puertas Abiertas'), ('suspension_completa', 'Suspensión de Actividades Completa'), ('suspension_parcial', 'Suspensión de Actividades Parcial')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='EventoAcademico',
        ),
    ]
